---

- name: GoLismero | Clone git repo
  git:
    repo: https://github.com/golismero/golismero.git
    dest: /opt/GoLismero
    clone: yes
    force: no
    depth: 1

- name: GoLismero | Install nmap
  package:
    name: nmap
    state: present

- name: GoLismero | Install sslscan
  package:
    name: sslscan
    state: present
  when: ansible_lsb.codename not in [ "buster" ]

- name: GoLismero | Install pip requirements
  pip:
    requirements: "{{ item }}"
    state: present
  with_items:
    - /opt/GoLismero/requirements.txt
    - /opt/GoLismero/requirements_unix.txt

- name: GoLismero | Make main script executable
  file:
    path: /opt/GoLismero/golismero.py
    mode: 0755

- name: GoLismero | Create link to main script
  file:
    path: /usr/local/bin/golismero
    state: link
    src: /opt/GoLismero/golismero.py
