---

- name: GoLismero | Clone git repo
  git:
    repo: https://github.com/golismero/golismero.git
    dest: /opt/GoLismero
    clone: yes
    force: yes
    depth: 1

- name: GoLismero | Install prerrequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nmap
    - sslscan

- name: GoLismero | Install pip requirements
  pip:
    requirements: "{{ item }}"
    state: present
  with_items:
    - /opt/GoLismero/requirements.txt
    - /opt/GoLismero/requirements_unix.txt

- name: GoLismero | Make main script executable
  file:
    path: /opt/GoLismero/golismero.py
    mode: 0755

- name: GoLismero | Create link to main script
  file:
    path: /usr/local/bin/golismero
    state: link
    src: /opt/GoLismero/golismero.py
