---
# tasks file for mablanco.sectools

- name: Install PIP
  include: pip.yml
  when: install_pip

- name: Install 'The Harvester'
  include: the_harvester.yml
  when: the_harvester

- name: Install 'GoLismero'
  include: golismero.yml
  when: golismero

- name: Install 'ReconScan'
  include: reconscan.yml
  when: reconscan

- name: Install 'WAScan'
  include: wascan.yml
  when: wascan

- name: Install 'ssh-audit'
  include: ssh-audit.yml
  when: ssh_audit
