---
# tasks file for mablanco.sectools

- name: Install 'GoLismero'
  include: golismero.yml
  when: golismero | bool

- name: Install 'ReconScan'
  include: reconscan.yml
  when: reconscan | bool

- name: Install 'WAScan'
  include: wascan.yml
  when: wascan | bool

- name: Install 'ssh-audit'
  include: ssh-audit.yml
  when: ssh_audit | bool

- name: Install 'testssl.sh'
  include: testssl.yml
  when: testssl | bool

- name: Install 'Pompem'
  include: pompem.yml
  when: pompem | bool
