---

- name: ReconScan | Clone git repo
  git:
    repo: https://github.com/RoliSoft/ReconScan.git
    dest: /opt/ReconScan
    clone: yes
    force: yes
    depth: 1

- name: ReconScan | Install prerrequisites
  package:
    name:
      - nmap
      - nikto
      - hydra
    state: latest

- name: ReconScan | Install pip requirements
  pip:
    executable: pip3
    name:
    - python-libnmap
    - colorama
    - lxml
    state: present

- name: ReconScan | Make scripts executable
  file:
    path: "/opt/ReconScan/{{ item }}"
    mode: 0755
  with_items:
    - recon.py
    - vulnscan.py

- name: ReconScan | Create links to scripts
  file:
    path: "/usr/local/bin/{{ item }}"
    state: link
    src: "/opt/ReconScan/{{ item }}.py"
  with_items:
    - recon
    - vulnscan
