---

- name: ReconScan | Clone git repo
  git:
    repo: https://github.com/RoliSoft/ReconScan.git
    dest: /opt/ReconScan
    clone: yes
    force: yes

- name: ReconScan | Install PIP3
  easy_install:
    name: pip
    executable: easy_install3
    state: latest

- name: ReconScan | Install prerrequisites
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - nmap
    - nikto
    - hydra

- name: ReconScan | Install pip requirements
  pip:
    executable: pip3
    state: present
    name: "{{item}}"
  with_items:
  - python-libnmap
  - colorama
  - lxml

- name: ReconScan | Make scripts executable
  file:
    path: "/opt/ReconScan/{{ item }}"
    mode: 0755
  with_items:
    - recon.py
    - vulnscan.py

- name: ReconScan | Create links to scripts
  file:
    path: "/usr/local/bin/{{ item }}"
    state: link
    src: "/opt/ReconScan/{{ item }}.py"
  with_items:
    - recon
    - vulnscan
