---

- name: WAScan | Clone git repo
  git:
    repo: https://github.com/m4ll0k/WAScan.git
    dest: /opt/wascan
    clone: yes
    force: no
    depth: 1
    version: master

- name: WAScan | Install pip requirements
  pip:
    name: BeautifulSoup
    state: present

- name: WAScan | Make main script executable
  file:
    path: /opt/wascan/wascan.py
    mode: 0755

- name: WAScan | Create link to main script
  file:
    path: /usr/local/bin/wascan
    state: link
    src: /opt/wascan/wascan.py
