---

- name: WAScan | Clone git repo
  git:
    repo: https://github.com/m4ll0k/WAScan.git
    dest: /opt/wascan
    clone: yes
    force: yes

- name: WAScan | Install PIP
  easy_install:
    name: pip
    state: latest

- name: WAScan | Install pip requirements
  pip:
    requirements: /opt/wascan/requirements.txt
    state: present

- name: WAScan | Make scripts executable
  file:
    path: "/opt/wascan/{{ item }}"
    mode: 0755
  with_items:
    - wascan.py

- name: WAScan | Create links to scripts
  file:
    path: "/usr/local/bin/{{ item }}"
    state: link
    src: "/opt/wascan/{{ item }}.py"
  with_items:
    - wascan
